name: Dev Build
on:
    push:
        branches:
            - dev
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        runs-on: ${{matrix.os}}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Prepare PNPM
              uses: pnpm/action-setup@v4

            - name: Prepare Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: pnpm

            - name: Install dependencies
              run: pnpm i

            - name: Build TypeScript
              run: pnpm build

            - name: Build Electron
              run: pnpm electron-builder -p always --x64 -- arm64 --universal
              env:
                  GH_TOKEN: ${{github.token}}
