name: Legacy branch build
on:
  push:
    branches:
      - legacy

env:
  FORCE_COLOR: true

jobs:
  build-legacywindows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Node dependencies
        run: pnpm install

      - name: Install Electron-Builder
        run: pnpm install -g electron-builder

      - name: Install Electron 22
        run: pnpm install electron@v22.3.27
        
      - name: Build
        run: pnpm run build && electron-builder --windows zip && electron-builder --windows zip --ia32

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ArmCordLegacyWindows
          path: dist/ArmCord-3.2.8-win.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ArmCordLegacyWindowsX86
          path: dist/ArmCord-3.2.8-ia32-win.zip
  build-macOS12:
    # macOS 10.11/10.12
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Node dependencies
        run: pnpm install

      - name: Install Electron-Builder
        run: pnpm install -g electron-builder

      - name: Install Electron 22
        run: pnpm install electron@v20.3.12
        
      - name: Build
        run: pnpm run build && electron-builder --macos zip --x64
        env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ArmCordLegacyMac12
          path: dist/ArmCord-3.2.8-mac.zip 
  build-macOS14:
    # macOS 10.13/10.14
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Node dependencies
        run: pnpm install

      - name: Install Electron-Builder
        run: pnpm install -g electron-builder

      - name: Install Electron 22
        run: pnpm install electron@v27.3.11
        
      - name: Build
        run: pnpm run build && electron-builder --macos zip --x64
        env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ArmCordLegacyMac14
          path: dist/ArmCord-3.2.8-mac.zip 
  release:
    runs-on: ubuntu-latest
    needs: [build-legacywindows, build-macOS12, build-macOS14]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: ArmCordLegacyWindows
          path: windows
      - uses: actions/download-artifact@v2
        with:
          name: ArmCordLegacyMac12
          path: mac
      - uses: actions/download-artifact@v2
        with:
          name: ArmCordLegacyWindowsX86
          path: windows
      - name: Rename macOS 10.11/10.12 zip
        run: mv mac/ArmCord-3.2.8-mac.zip mac/ArmCord-Legacy-e20-mac.zip
      - name: Rename E22 zip
        run: mv windows/ArmCord-3.2.8-win.zip windows/ArmCord-Legacy-e22-win7.zip
      - name: Rename E22 x86 zip
        run: mv windows/ArmCord-3.2.8-ia32-win.zip windows/ArmCord-Legacy-ia32-e22-win7.zip
      - uses: actions/download-artifact@v2
        with:
          name: ArmCordLegacyMac14
          path: mac
      - name: Rename macOS 10.13/10.14 zip
        run: mv mac/ArmCord-3.2.8-mac.zip mac/ArmCord-Legacy-e27-mac.zip
      - name: Get some values needed for the release
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: legacybuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create the release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: legacybuild
          name: ArmCord Legacy Build ${{ steps.vars.outputs.sha_short }}
          draft: false
          prerelease: true
          body_path: .github/legacy.md
          files: |
            windows/ArmCord-Legacy-e22-win7.zip
            windows/ArmCord-Legacy-ia32-e22-win7.zip
            mac/ArmCord-Legacy-e27-mac.zip
            mac/ArmCord-Legacy-e20-mac.zip
