name: Package
on:
  push:
      branches: dev
jobs:
    package:
        continue-on-error: true
        strategy:
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]
        runs-on: ${{matrix.os}}
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Build TypeScript
              uses: ./.github/actions/build-typescript

            - name: Install SnapCraft
              if: matrix.os == 'macos-latest'
              uses: samuelmeuli/action-snapcraft@v2

            - name: Load Electron cache
              uses: actions/cache/restore@v4
              with:
                  path: .cache
                  key: electron-zips.${{matrix.os}}

            # Sadly, it makes more sense to separate builds per platform
            - name: Build Electron for MacOS
              if: matrix.os == 'macos-latest'
              run: pnpm electron-builder --universal -m
              env:
                CSC_KEY_PASSWORD: ${{ secrets.MACOS_SIGN_PASS }}
                APPLE_ID: ${{secrets.APPLE_ID}}
                APPLE_APP_SPECIFIC_PASSWORD: ${{secrets.APPLE_ID_PASSWORD}}
                APPLE_TEAM_ID: ${{secrets.APPLE_TEAM_ID}}

            - name: Build Electron for Linux
              if: matrix.os == 'macos-latest'
              run: pnpm electron-builder --armv7l --arm64 --x64 -l snap appimage deb rpm zip

            - name: Build Electron for Windows
              if: matrix.os == 'windows-latest'
              run: pnpm electron-builder --ia32 --arm64 --x64 -w nsis zip

            - name: Build Electron for Linux (RPM)
              if: matrix.os == 'macos-latest'
              run: pnpm electron-builder --armv7l --arm64 --x64 -l rpm

            - name: Save Electron Cache
              uses: actions/cache/save@v4
              with:
                  path: .cache
                  key: electron-zips.${{matrix.os}}

            - name: Collect artifacts
              run: 
                mkdir artifacts |
                find dist/. -maxdepth 1 -type f -exec mv -t artifacts {} +
              shell: bash
            
            - name: Upload artifactsstable
              uses: actions/upload-artifact@v4
              with:
                name: ${{matrix.os}}-artifacts
                path: artifacts/*

    dev-release:
        runs-on: ubuntu-latest
        needs:
            - package
        steps:
          - name: Download artifacts
            uses: actions/download-artifact@v4
            with:
              path: release-files

          - name: Create release
            uses: ncipollo/release-action@v1
            env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            with:
                name: Rolling Dev Build
                allowUpdates: true
                removeArtifacts: true
                prerelease: true
                body: "Built against https://github.com/Legcord/Legcord/tree/dev on every commit. NOTE: tarballs do not update."
                draft: false
                tag: devbuild
                artifacts: release-files/**/*